server:
  port: 8085


 ###########springboot配置###########
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mytest?serverTimezone=UTC&useSSL=false&autoReconnect=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: root123
    driver-class-name: com.mysql.jdbc.Driver
##################redis配置文件##################
  redis:
    #redis数据库索引(默认为0),我们使用索引为3的数据库，说是为了避免和其他数据库发生冲突
    database: 3
    host: 192.168.8.116
    port: 6379
    password:

  timeout: 0


###########Mybatis###################
mybatis-plus:
  mapper-locations: classpath*:com/example/demo/pos/dao/mapping/*.xml
  type-aliases-package: com.example.demo.pos.dao.model

  global-config:
    id-type: 0
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性

